name: gpt
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-285.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  easy_localization: ^3.0.3
  get: ^4.6.5
  shared_preferences: ^2.0.8
  font_awesome_flutter: ^10.2.1
  http: ^1.1.0
  progress_indicators: ^1.0.0
  timezone: ^0.9.2
  platform_device_id_v3: ^1.0.0
  package_info_plus: ^4.1.0
  sliding_clipped_nav_bar: ^3.1.0+4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/translations/

  fonts:
    - family: IRANSansX
      fonts:
        - asset: assets/fonts/IRANSansXFaNum-Regular.otf
